(function () {
const CHICAGO_CENTER=[41.8781,-87.6298],GEO='https://raw.githubusercontent.com/blackmad/neighborhoods/master/chicago.geojson';
const state={map:null,mode:'free',activity:'run',color:'#f43f5e',distanceUnits:localStorage.getItem('catchme-distance-units')||'km',runWatchId:null,runPath:[],totalKm:0,startTs:null,timer:null,claimsLayer:null,runnerLine:null,freeClaims:[],teamClaims:[]};
const ui={};
const toDist=(km)=>state.distanceUnits==='mi'?(km*0.621371).toFixed(2):km.toFixed(2);
const fmtTime=(ms)=>{const s=Math.floor(ms/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
function claims(){return state.mode==='free'?state.freeClaims:state.teamClaims}
function msg(t){ui.message.textContent=t}
function refreshStats(){const elapsed=state.startTs?Date.now()-state.startTs:0;ui.runtime.textContent=fmtTime(elapsed);ui.distance.textContent=toDist(state.totalKm);const hrs=elapsed/3600000;const dist=state.distanceUnits==='mi'?state.totalKm*0.621371:state.totalKm;ui.speed.textContent=hrs>0?(dist/hrs).toFixed(1):'0.0';}
function renderSavedAreas(){const mine=claims().slice(-6).reverse();ui.savedAreas.innerHTML=mine.map(c=>`<div class="saved-area-pill">${c.name||'Area'} · ${(c.area/1000000).toFixed(2)} km²</div>`).join('')||'<div class="saved-area-pill">No saved areas yet.</div>'}
async function loadMap(){const res=await fetch(GEO);const geo=await res.json();L.geoJSON(geo,{style:{fillOpacity:.35,color:'#334155',weight:1}}).addTo(state.map)}
function renderClaims(){state.claimsLayer.clearLayers();claims().forEach(c=>L.geoJSON(c.geojson,{style:{fillColor:c.color,fillOpacity:.45,color:c.color,weight:2}}).addTo(state.claimsLayer));renderSavedAreas()}
function setMode(m){state.mode=m;ui.freeBtn.classList.toggle('active',m==='free');ui.teamBtn.classList.toggle('active',m==='team');renderClaims()}
function startRun(){if(state.runWatchId!==null)return;state.runPath=[];state.totalKm=0;state.startTs=Date.now();refreshStats();if(state.timer)clearInterval(state.timer);state.timer=setInterval(refreshStats,1000);ui.startBtn.classList.add('recording');ui.startBtn.innerHTML='⏹️<small>Stop</small>';msg(`Started ${state.activity}.`);state.runWatchId=navigator.geolocation.watchPosition(onPos,onErr,{enableHighAccuracy:true,maximumAge:0,timeout:8000});}
function stopRun(show=true){if(state.runWatchId!==null)navigator.geolocation.clearWatch(state.runWatchId);state.runWatchId=null;if(state.timer)clearInterval(state.timer);state.timer=null;ui.startBtn.classList.remove('recording');ui.startBtn.innerHTML='▶️<small>Start</small>';if(show)msg(`Stopped. Final time ${ui.runtime.textContent}.`)}
function onPos(pos){const p=[pos.coords.longitude,pos.coords.latitude];const last=state.runPath[state.runPath.length-1];if(last){const km=turf.distance(turf.point(last),turf.point(p),{units:'kilometers'});if(km>0.002&&km<0.3)state.totalKm+=km;}state.runPath.push(p);state.runnerLine.setLatLngs(state.runPath.map(x=>[x[1],x[0]]));refreshStats();msg(`Tracking ${state.activity} · ${toDist(state.totalKm)} ${state.distanceUnits}`);if(state.runPath.length>8&&turf.distance(turf.point(state.runPath[0]),turf.point(p),{units:'kilometers'})<0.05){completeLoop();}}
function onErr(e){msg(`GPS error ${e.code}`);stopRun(false)}
function completeLoop(){const poly=turf.polygon([[...state.runPath,state.runPath[0]]]);const name=(prompt('Name this capture area:','My Loop')||'My Loop').trim();const claim={name,color:state.color,geojson:poly,area:turf.area(poly)};claims().push(claim);renderClaims();msg(`Saved ${name}. Time ${ui.runtime.textContent}. Distance ${ui.distance.textContent} ${state.distanceUnits}`);stopRun(false)}
async function init(){if(state.map)return;ui.freeBtn=document.getElementById('catchme-free');ui.teamBtn=document.getElementById('catchme-team');ui.units=document.getElementById('catchme-units');ui.style=document.getElementById('catchme-style');ui.message=document.getElementById('catchme-message');ui.runtime=document.getElementById('catchme-runtime');ui.distance=document.getElementById('catchme-distance');ui.speed=document.getElementById('catchme-speed');ui.activityBtn=document.getElementById('catchme-activity');ui.startBtn=document.getElementById('catchme-start-run');ui.profileBtn=document.getElementById('catchme-profile');ui.profileSheet=document.getElementById('catchme-profile-sheet');ui.color=document.getElementById('catchme-color');ui.username=document.getElementById('catchme-username');ui.savedAreas=document.getElementById('catchme-saved-areas');ui.center=document.getElementById('catchme-center-map');ui.drawer=document.getElementById('catchme-drawer');ui.drawerToggle=document.getElementById('catchme-drawer-toggle');
state.map=L.map('catchme-map',{zoomControl:false}).setView(CHICAGO_CENTER,12);L.control.zoom({position:'bottomright'}).addTo(state.map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20}).addTo(state.map);state.claimsLayer=L.layerGroup().addTo(state.map);state.runnerLine=L.polyline([],{color:state.color,weight:4}).addTo(state.map);await loadMap();
ui.freeBtn.onclick=()=>setMode('free');ui.teamBtn.onclick=()=>setMode('team');ui.startBtn.onclick=()=>state.runWatchId===null?startRun():stopRun(true);ui.activityBtn.onclick=()=>{state.activity=state.activity==='run'?'walk':'run';ui.activityBtn.innerHTML=state.activity==='run'?'🏃<small>Run</small>':'🚶<small>Walk</small>';};ui.profileBtn.onclick=()=>ui.profileSheet.style.display=ui.profileSheet.style.display==='none'?'block':'none';ui.color.oninput=(e)=>{state.color=e.target.value;state.runnerLine.setStyle({color:state.color})};ui.units.value=state.distanceUnits;ui.units.onchange=(e)=>{state.distanceUnits=e.target.value;localStorage.setItem('catchme-distance-units',state.distanceUnits);refreshStats();};ui.center.onclick=()=>state.map.setView(CHICAGO_CENTER,12);ui.drawerToggle.onclick=()=>{ui.drawer.classList.toggle('collapsed');ui.drawerToggle.textContent=ui.drawer.classList.contains('collapsed')?'⌃':'⌄';};ui.username.value=window.currentUser?.displayName||'';setMode('free');refreshStats();}
window.initCatchMe=async()=>{await init();setTimeout(()=>state.map.invalidateSize(),120)};
})();
