// Game Data for Tessa's Games

// Wordle words - customizable for Tessa
const wordleWords = [
    'TESSA',
    'ANGEL',
    'HEART',
    'SMILE',
    'HAPPY',
    'SWEET',
    'LOVED',
    'DREAM',
    'MAGIC',
    'PEARL',
    'GRACE',
    'SHINE',
    'BLOOM',
    'CHARM',
    'BLISS',
    'ADORE',
    'DANCE',
    'BRAVE',
    'PRIDE',
    'ALIVE',
    'BRISK',
    'CLOUD',
    'FAITH',
    'GLOOM',
    'GLORY',
    'HONEY',
    'IVORY',
    'JOLLY',
    'KITES',
    'LEMON',
    'MIRTH',
    'NOBLE',
    'OCEAN',
    'PAUSE',
    'QUILT',
    'RIVER',
    'SCALE',
    'TEASE',
    'UNITY',
    'VIVID',
    'WALTZ',
    'XENON',
    'YOUTH',
    'ZEBRA',
    'APPLE',
    'BERRY',
    'CANDY',
    'DIZZY',
    'EAGER',
    'FROST',
    'GIANT',
    'HUMOR',
    'IDEAL',
    'JELLY',
    'KNACK',
    'LILAC',
    'MAPLE',
    'NURSE',
    'OPERA',
    'PEACH',
    'QUIET',
    'ROBIN',
    'SHEEP',
    'TIGER',
    'ULTRA',
    'VENUS',
    'WINDY',
    'YEARN',
    'ZESTY',
    'AMBER',
    'BUNNY',
    'CRISP',
    'DRIFT',
    'ELATE',
    'FLUTE',
    'GHOST',
    'HUMID',
    'INBOX',
    'JUMBO',
    'KOALA',
    'LATCH',
    'MANGO',
    'NINJA',
    'OASIS',
    'PANDA',
    'QUICK',
    'ROAST',
    'SALTY',
    'TULIP',
    'URBAN',
    'VIRUS',
    'WHEAT',
    'YACHT',
    'ZONAL',
    'AWAKE',
    'BEACH',
    'CHIME',
    'DELTA',
    'EPOCH',
    'FABLE',
    'GAZER',
    'HASTE',
    'INDEX',
    'JOKER',
    'KARMA',
    'LUNAR',
    'METAL',
    'NACHO',
    'OTTER',
    'PLUME',
    'QUEST',
    'RHYME',
    'SUSHI',
    'TANGO',
    'UNION',
    'VAPOR',
    'WHISK',
    'YUMMY',
    'ZIPPY',
    'ABOUT',
    'ABOVE',
    'ACTOR',
    'ACUTE',
    'ADAPT',
    'ADEPT',
    'ADMIN',
    'ADMIT',
    'ADOPT',
    'ADULT',
    'AFTER',
    'AGAIN',
    'AGILE',
    'AGREE',
    'AHEAD',
    'AISLE',
    'ALERT',
    'ALBUM',
    'ALLOW',
    'ALOFT',
    'ALONE',
    'ALONG',
    'ALOUD',
    'ALTER',
    'AMASS',
    'AMPLE',
    'ANGLE',
    'ANGRY',
    'ANKLE',
    'ANNOY',
    'ANTIC',
    'APRON',
    'ARBOR',
    'ARENA',
    'ARGUE',
    'ARISE',
    'ARMOR',
    'ARRAY',
    'ARROW',
    'ASIDE',
    'ASSET',
    'AUDIO',
    'AUDIT',
    'AWAIT',
    'AWARD',
    'AWARE',
    'AXIOM',
    'AZURE',
    'BACON',
    'BADGE',
    'BAGEL',
    'BAKER',
    'BALER',
    'BALMY',
    'BANJO',
    'BASIN',
    'BATCH',
    'BATON',
    'BAZAR',
    'BEARD',
    'BEAST',
    'BEGIN',
    'BELOW',
    'BICEP',
    'BINGO',
    'BISON',
    'BLACK',
    'BLADE',
    'BLANK',
    'BLAST',
    'BLAZE',
    'BLEND',
    'BLINK',
    'BLUNT',
    'BOARD',
    'BOAST',
    'BONUS',
    'BOOST',
    'BRAIN',
    'BRAND',
    'BRASS',
    'BREAD',
    'BREAK',
    'BRICK',
    'BRIDE',
    'BRING',
    'BROAD',
    'BROIL',
    'BROKE',
    'BROWN',
    'BRUSH',
    'BUILD',
    'BUILT',
    'BURST',
    'CABLE',
    'CADDY',
    'CAMEL',
    'CANAL',
    'CAPER',
    'CARGO',
    'CARRY',
    'CARVE',
    'CATCH',
    'CAUSE',
    'CEASE',
    'CEDAR',
    'CHAIR',
    'CHALK',
    'CHASE',
    'CHEAP',
    'CHECK',
    'CHEER',
    'CHESS',
    'CHEST',
    'CHIEF',
    'CHILD',
    'CHILI',
    'CHORD',
    'CHOSE',
    'CIDER',
    'CIGAR',
    'CIRCA',
    'CIVIC',
    'CLAIM',
    'CLAMP',
    'CLASH',
    'CLASS',
    'CLEAN',
    'CLEAR',
    'CLEFT',
    'CLERK',
    'CLICK',
    'CLIFF',
    'CLIMB',
    'CLOCK',
    'CLOSE',
    'CLOTH',
    'CLOWN',
    'COACH',
    'COAST',
    'COBRA',
    'COCOA',
    'COLON',
    'COLOR',
    'COMBO',
    'COMET',
    'COMFY',
    'COMIC',
    'CORAL',
    'CORNY',
    'COUCH',
    'COULD',
    'COUNT',
    'COURT',
    'COVEN',
    'COVER',
    'CRANE',
    'CRANK',
    'CRASH',
    'CREAM',
    'CREEP',
    'CREST',
    'CRIME',
    'CROSS',
    'CROWD',
    'CROWN',
    'CRUDE',
    'CRUEL',
    'CRUMB',
    'CRUSH',
    'CURVE',
    'CYCLE',
    'DAIRY',
    'DAISY',
    'DANDY',
    'DEBIT',
    'DEBUG',
    'DECAL',
    'DECAY',
    'DECOR',
    'DELAY',
    'DEPTH',
    'DETER',
    'DEVIL',
    'DIARY',
    'DIGIT',
    'DITCH',
    'DIVER',
    'DODGE',
    'DONUT',
    'DOUBT',
    'DOZEN',
    'DRAFT',
    'DRAMA',
    'DRAWN',
    'DREAD',
    'DRESS',
    'DRINK',
    'DRIVE',
    'DROVE',
    'DROWN',
    'DRUID',
    'DRYER',
    'DUSTY',
    'DWARF',
    'EAGLE',
    'EARLY',
    'EARTH',
    'EASEL',
    'EATEN',
    'EBONY',
    'ELBOW',
    'ELDER',
    'ELECT',
    'ELFIN',
    'ELITE',
    'EMBER',
    'EMPTY',
    'ENACT',
    'ENJOY',
    'ENROL',
    'ENTER',
    'ENTRY',
    'EQUAL',
    'EQUIP',
    'ERASE',
    'ERROR',
    'ESSAY',
    'EVENT',
    'EVERY',
    'EXACT',
    'EXALT',
    'EXCEL',
    'EXERT',
    'EXIST',
    'EXTRA',
    'FAINT',
    'FAIRY',
    'FALSE',
    'FANCY',
    'FANGS',
    'FERRY',
    'FEAST',
    'FEVER',
    'FIBER',
    'FIELD',
    'FIERY',
    'FIFTH',
    'FIFTY',
    'FIGHT',
    'FINAL',
    'FINCH',
    'FIXER',
    'FJORD',
    'FLAIL',
    'FLAIR',
    'FLAME',
    'FLASH',
    'FLEET',
    'FLICK',
    'FLOOD',
    'FLOUR',
    'FLOWN',
    'FOCUS',
    'FOLIO',
    'FORGE',
    'FORTH',
    'FORTY',
    'FOUND',
    'FRAME',
    'FRANK',
    'FRAUD',
    'FRESH',
    'FRIED',
    'FRONT',
    'FROWN',
    'FRUIT',
    'FUDGE',
    'FUNNY',
    'GAINS',
    'GAMER',
    'GAMMA',
    'GAVEL',
    'GENIE',
    'GENRE',
    'GIDDY',
    'GIPSY',
    'GLASS',
    'GLIDE',
    'GLOBE',
    'GLUED',
    'GRAIN',
    'GRANT',
    'GRASP',
    'GRASS'
];

// Crossword clue bank for auto-generated puzzles
const crosswordClueBank = {
    GARDENS: 'Places with flowers and paths',
    RAINBOW: 'Colorful arc after rain',
    HARMONY: 'Pleasant musical blend',
    JOURNEY: 'Long trip',
    ORCHARD: 'Fruit tree grove',
    HORIZON: 'Skyline boundary',
    PLAYFUL: 'Full of fun',
    WHISPER: 'Soft spoken sound',
    LIBRARY: 'Place to borrow books',
    MEADOWS: 'Open grassy fields',
    LANTERN: 'Portable light',
    COMPASS: 'Directional instrument',
    SEASIDE: 'Coastline area',
    CUPCAKE: 'Small frosted dessert',
    KINDRED: 'Related by family',
    SEASALT: 'Ocean mineral seasoning',
    STARLIT: 'Lit by stars',
    SUNBEAM: 'Ray of sunlight'
};

// Crossword puzzles - 15x15 daily rotation (no 3-letter words)
const crosswordPuzzles = [
    {
        grid: [
            'GARDENS#RAINBOW',
            'HARMONY#JOURNEY',
            'ORCHARD#HORIZON',
            'PLAYFUL#WHISPER',
            'LIBRARY#MEADOWS',
            'LANTERN#COMPASS',
            'SEASIDE#CUPCAKE',
            'KINDRED#SEASALT',
            'STARLIT#SUNBEAM',
            'RAINBOW#GARDENS',
            'JOURNEY#HARMONY',
            'HORIZON#ORCHARD',
            'WHISPER#PLAYFUL',
            'MEADOWS#LIBRARY',
            'COMPASS#LANTERN'
        ]
    },
    {
        grid: [
            'HARMONY#JOURNEY',
            'ORCHARD#HORIZON',
            'PLAYFUL#WHISPER',
            'LIBRARY#MEADOWS',
            'LANTERN#COMPASS',
            'SEASIDE#CUPCAKE',
            'KINDRED#SEASALT',
            'STARLIT#SUNBEAM',
            'GARDENS#RAINBOW',
            'JOURNEY#HARMONY',
            'HORIZON#ORCHARD',
            'WHISPER#PLAYFUL',
            'MEADOWS#LIBRARY',
            'COMPASS#LANTERN',
            'RAINBOW#GARDENS'
        ]
    },
    {
        grid: [
            'ORCHARD#HORIZON',
            'PLAYFUL#WHISPER',
            'LIBRARY#MEADOWS',
            'LANTERN#COMPASS',
            'SEASIDE#CUPCAKE',
            'KINDRED#SEASALT',
            'STARLIT#SUNBEAM',
            'GARDENS#RAINBOW',
            'HARMONY#JOURNEY',
            'HORIZON#ORCHARD',
            'WHISPER#PLAYFUL',
            'MEADOWS#LIBRARY',
            'COMPASS#LANTERN',
            'RAINBOW#GARDENS',
            'JOURNEY#HARMONY'
        ]
    }
];

// Sudoku puzzles - various difficulty levels
const sudokuPuzzles = [
    {
        // Easy puzzle
        puzzle: [
            [5, 3, 0, 0, 7, 0, 0, 0, 0],
            [6, 0, 0, 1, 9, 5, 0, 0, 0],
            [0, 9, 8, 0, 0, 0, 0, 6, 0],
            [8, 0, 0, 0, 6, 0, 0, 0, 3],
            [4, 0, 0, 8, 0, 3, 0, 0, 1],
            [7, 0, 0, 0, 2, 0, 0, 0, 6],
            [0, 6, 0, 0, 0, 0, 2, 8, 0],
            [0, 0, 0, 4, 1, 9, 0, 0, 5],
            [0, 0, 0, 0, 8, 0, 0, 7, 9]
        ],
        solution: [
            [5, 3, 4, 6, 7, 8, 9, 1, 2],
            [6, 7, 2, 1, 9, 5, 3, 4, 8],
            [1, 9, 8, 3, 4, 2, 5, 6, 7],
            [8, 5, 9, 7, 6, 1, 4, 2, 3],
            [4, 2, 6, 8, 5, 3, 7, 9, 1],
            [7, 1, 3, 9, 2, 4, 8, 5, 6],
            [9, 6, 1, 5, 3, 7, 2, 8, 4],
            [2, 8, 7, 4, 1, 9, 6, 3, 5],
            [3, 4, 5, 2, 8, 6, 1, 7, 9]
        ]
    },
    {
        // Medium puzzle
        puzzle: [
            [0, 0, 0, 6, 0, 0, 4, 0, 0],
            [7, 0, 0, 0, 0, 3, 6, 0, 0],
            [0, 0, 0, 0, 9, 1, 0, 8, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 5, 0, 1, 8, 0, 0, 0, 3],
            [0, 0, 0, 3, 0, 6, 0, 4, 5],
            [0, 4, 0, 2, 0, 0, 0, 6, 0],
            [9, 0, 3, 0, 0, 0, 0, 0, 0],
            [0, 2, 0, 0, 0, 0, 1, 0, 0]
        ],
        solution: [
            [5, 8, 1, 6, 7, 2, 4, 3, 9],
            [7, 9, 2, 8, 4, 3, 6, 5, 1],
            [3, 6, 4, 5, 9, 1, 7, 8, 2],
            [4, 3, 8, 9, 5, 7, 2, 1, 6],
            [2, 5, 6, 1, 8, 4, 9, 7, 3],
            [1, 7, 9, 3, 2, 6, 8, 4, 5],
            [8, 4, 5, 2, 1, 9, 3, 6, 7],
            [9, 1, 3, 7, 6, 8, 5, 2, 4],
            [6, 2, 7, 4, 3, 5, 1, 9, 8]
        ]
    },
    {
        // Another easy puzzle
        puzzle: [
            [0, 0, 0, 2, 6, 0, 7, 0, 1],
            [6, 8, 0, 0, 7, 0, 0, 9, 0],
            [1, 9, 0, 0, 0, 4, 5, 0, 0],
            [8, 2, 0, 1, 0, 0, 0, 4, 0],
            [0, 0, 4, 6, 0, 2, 9, 0, 0],
            [0, 5, 0, 0, 0, 3, 0, 2, 8],
            [0, 0, 9, 3, 0, 0, 0, 7, 4],
            [0, 4, 0, 0, 5, 0, 0, 3, 6],
            [7, 0, 3, 0, 1, 8, 0, 0, 0]
        ],
        solution: [
            [4, 3, 5, 2, 6, 9, 7, 8, 1],
            [6, 8, 2, 5, 7, 1, 4, 9, 3],
            [1, 9, 7, 8, 3, 4, 5, 6, 2],
            [8, 2, 6, 1, 9, 5, 3, 4, 7],
            [3, 7, 4, 6, 8, 2, 9, 1, 5],
            [9, 5, 1, 7, 4, 3, 6, 2, 8],
            [5, 1, 9, 3, 2, 6, 8, 7, 4],
            [2, 4, 8, 9, 5, 7, 1, 3, 6],
            [7, 6, 3, 4, 1, 8, 2, 5, 9]
        ]
    },
    {
        // Easy variation
        puzzle: [
            [5, 0, 0, 0, 7, 0, 0, 1, 0],
            [0, 7, 0, 1, 0, 5, 0, 0, 8],
            [1, 0, 8, 0, 0, 2, 0, 6, 0],
            [0, 5, 0, 7, 0, 0, 4, 0, 3],
            [4, 0, 6, 0, 5, 0, 7, 0, 1],
            [0, 1, 0, 9, 0, 4, 0, 5, 0],
            [9, 0, 0, 5, 3, 0, 2, 0, 4],
            [0, 8, 0, 4, 0, 9, 0, 3, 0],
            [3, 0, 5, 0, 8, 0, 1, 0, 9]
        ],
        solution: [
            [5, 3, 4, 6, 7, 8, 9, 1, 2],
            [6, 7, 2, 1, 9, 5, 3, 4, 8],
            [1, 9, 8, 3, 4, 2, 5, 6, 7],
            [8, 5, 9, 7, 6, 1, 4, 2, 3],
            [4, 2, 6, 8, 5, 3, 7, 9, 1],
            [7, 1, 3, 9, 2, 4, 8, 5, 6],
            [9, 6, 1, 5, 3, 7, 2, 8, 4],
            [2, 8, 7, 4, 1, 9, 6, 3, 5],
            [3, 4, 5, 2, 8, 6, 1, 7, 9]
        ]
    },
    {
        // Medium variation
        puzzle: [
            [0, 8, 1, 0, 7, 0, 4, 0, 9],
            [7, 0, 0, 8, 0, 3, 0, 5, 0],
            [0, 6, 0, 5, 0, 1, 7, 0, 2],
            [4, 0, 8, 0, 5, 0, 2, 1, 0],
            [0, 5, 0, 1, 0, 4, 0, 7, 0],
            [1, 0, 9, 0, 2, 0, 8, 0, 5],
            [0, 4, 0, 2, 1, 0, 3, 0, 7],
            [9, 0, 3, 0, 6, 8, 0, 2, 0],
            [0, 2, 7, 4, 0, 5, 1, 0, 8]
        ],
        solution: [
            [5, 8, 1, 6, 7, 2, 4, 3, 9],
            [7, 9, 2, 8, 4, 3, 6, 5, 1],
            [3, 6, 4, 5, 9, 1, 7, 8, 2],
            [4, 3, 8, 9, 5, 7, 2, 1, 6],
            [2, 5, 6, 1, 8, 4, 9, 7, 3],
            [1, 7, 9, 3, 2, 6, 8, 4, 5],
            [8, 4, 5, 2, 1, 9, 3, 6, 7],
            [9, 1, 3, 7, 6, 8, 5, 2, 4],
            [6, 2, 7, 4, 3, 5, 1, 9, 8]
        ]
    },
    {
        // Easy variation
        puzzle: [
            [4, 0, 5, 0, 6, 0, 7, 8, 0],
            [0, 8, 0, 5, 0, 1, 0, 9, 0],
            [1, 0, 0, 8, 3, 0, 5, 0, 2],
            [0, 2, 6, 0, 9, 5, 0, 4, 0],
            [3, 0, 4, 6, 0, 2, 9, 0, 5],
            [0, 5, 0, 7, 4, 0, 6, 2, 0],
            [5, 1, 0, 3, 0, 6, 0, 7, 4],
            [0, 4, 8, 0, 5, 0, 1, 0, 6],
            [7, 0, 3, 4, 0, 8, 2, 0, 9]
        ],
        solution: [
            [4, 3, 5, 2, 6, 9, 7, 8, 1],
            [6, 8, 2, 5, 7, 1, 4, 9, 3],
            [1, 9, 7, 8, 3, 4, 5, 6, 2],
            [8, 2, 6, 1, 9, 5, 3, 4, 7],
            [3, 7, 4, 6, 8, 2, 9, 1, 5],
            [9, 5, 1, 7, 4, 3, 6, 2, 8],
            [5, 1, 9, 3, 2, 6, 8, 7, 4],
            [2, 4, 8, 9, 5, 7, 1, 3, 6],
            [7, 6, 3, 4, 1, 8, 2, 5, 9]
        ]
    }
];
